apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/operator
  - workload-namespace.yaml
  - workload-role.yaml
  - workload-role-binding.yaml
patches:
  - path: cluster-role.yaml
  - path: deployment.yaml
