apiVersion: runtime.polykube.dev/v1alpha1
kind: Workload
metadata:
  name: echo
  namespace: default
spec:
  federationRef:
    name: local-dev
  image: hashicorp/http-echo:latest
  replicas: 1
  ports:
    - name: http
      containerPort: 5678
  env:
    - name: TEXT
      value: "hello from polykube"
