apiVersion: v1
kind: ServiceAccount
metadata:
  name: polykube-operator
  namespace: polykube-system
  labels:
    app.kubernetes.io/name: polykube-operator
    app.kubernetes.io/part-of: polykube
    app.kubernetes.io/managed-by: gitops
