#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "${repo_root}/operator"

go tool controller-gen \
  object \
  crd \
  paths="./api/..." \
  output:crd:artifacts:config=config/crd/bases

for crd_path in config/crd/bases/*.yaml; do
  if [[ ! -f "${crd_path}" ]]; then
    continue
  fi

  if [[ "$(head -n 1 "${crd_path}")" == "# Code generated by controller-gen. DO NOT EDIT." ]]; then
    continue
  fi

  tmp_path="${crd_path}.tmp"
  {
    printf '# Code generated by controller-gen. DO NOT EDIT.\n'
    cat "${crd_path}"
  } >"${tmp_path}"
  mv "${tmp_path}" "${crd_path}"
done
